// newsletter-signup-with-success/vue/src/App.vue
<script setup>
import Landing from "./components/Landing.vue";
import Success from "./components/Success.vue";
</script>

<script>
export default {
  components: {
    Landing,
    Success,
  },
  data() {
    return {
      showLanding: true,
      showSuccess: false,
    };
  },
  methods: {
    toggle() {
      this.showLanding = !this.showLanding;
      this.showSuccess = !this.showSuccess;
    },
  },
};
</script>

<template>
  <Landing v-if="showLanding" @toggle="toggle" />
  <Success v-if="showSuccess" @toggle="toggle" />
</template>

// newsletter-signup-with-success/svelte/src/App.svelte
<script>
  import Landing from './lib/Landing.svelte';
  import Success from './lib/Success.svelte';

  let showLanding = true;
  let showSuccess = false;

  function toggle() {
    showSuccess = !showSuccess;
    showLanding = !showLanding;
  }
</script>

<main>
  {#if showLanding}
  <Landing {toggle}/>
  {/if}
  {#if showSuccess}
    <Success {toggle}/>
  {/if}
</main>

<style>

</style>
