// newsletter-signup-with-success/react/src/components/Success.jsx
import successCheck from "../assets/images/icon-list.svg";

const Success = ({ setLanding }) => {
  return (
    <section className="success-wrapper">
      <img src={successCheck} />
      <h3>Thanks for subscribing!</h3>
      <p>
        A confirmation email has been sent to
        <span id="user-email"></span> Please open it and click the button inside
        to confirm your subscription.
      </p>
      <button onClick={setLanding} className="dismiss-button">
        Dismiss message
      </button>
    </section>
  );
};
export default Success;

// newsletter-signup-with-success/angular/src/app/success/success.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-success',
  templateUrl: './success.component.html',
  styleUrls: ['./success.component.css'],
})
export class SuccessComponent {
  @Output() toggle = new EventEmitter<void>();
  emitEvent(event: MouseEvent) {
    event?.preventDefault();
    this.toggle.emit();
  }
}

<section class="success-wrapper">
  <img class="success-check" src="assets/images/icon-success.svg" />
  <h3>Thanks for subscribing!</h3>
  <p>
    A confirmation email has been sent to
    <span id="user-email"></span> Please open it and click the button inside to
    confirm your subscription.
  </p>
  <button (click)="emitEvent($event)" class="dismiss-button">
    Dismiss message
  </button>
</section>
